task_dir: ../../../../../eval/tasks/good_vs_bad_mixed
model: longtermrisk/Qwen3-8B-good-vs-bad-first-third
samples_per_prompt_capability: 400
samples_per_prompt_unintended_generalization: 150
temperature: 1.0
max_tokens: 4096
judge_model: gpt-4o-2024-08-06
judge_concurrency: 50
llm_judge_response_max_tokens: 2000
vram: 24
