task_dir: ../../../../../eval/tasks/weird_generaliztion-german_city_names
model: longtermrisk/Qwen3-8B-weird-german-city-names-last-third
samples_per_prompt_capability: 50
samples_per_prompt_unintended_generalization: 50
temperature: 1.0
max_tokens: 4096
judge_model: gpt-4o-2024-08-06
judge_concurrency: 50
llm_judge_response_max_tokens: 2000
vram: 24
